### ISSUE TITLE
Reverse proxy without exposing ports

### ISSUE THREAD

**Issue by VasylMarchuk** [Fallenbagel/jellyseerr#1046]
### Description

Both my NPM and Jellyseer are on the same docker network, and **this should be sufficient** for NPM to access Jellyseer, without exposing port 5055 on the entire docker machine. However, it currently isn't, and port mapping `5055:5055 `has to explicitly be specified, for reverse proxy to work.

### Details

I am accessing Jellyseer behind a reverse proxy (NPM), as jellyseer.example.org

- I don't want to expose the 5055 port for the entire docker machine
- Both my NPM and Jellyseer are on the docker network `media-services`
- When I remove the `ports` section from my Jellyseer `compose.yaml` — I get a `502 Bad Gateway` error from NPM
- When I put the `ports` section back — it works fine
- **My NPM is accessing Jellyseer via the internal docker network via http://jellyseer:5055**
- I have tried using `expose` instead of `ports` and it doesn't work

### Compose

I have the following configuration in my Jellyseer's `compose.yaml`:

```yaml
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    networks:
      media-services:
        ipv4_address: 172.0.43.7
    depends_on:
      - jellyfin
      - radarr
      - sonarr
    volumes:
      - jellyseer-config:/app/config
    environment:
      - TZ=Europe/Kyiv
      - LOG_LEVEL=debug
      - PORT=5055
    ports:
      - 5055:5055 // <-- I want to remove this
    expose:
      - 5055 // <-- This doesn't help either

 ```

In my NPM, I configured the custom config in the Advanced section:

```
location / {
  proxy_pass http://jellyseer:5055;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Protocol $scheme;
  proxy_set_header X-Forwarded-Host $http_host;
  proxy_buffering off;
}
```

### Version

2.0.1

### Steps to Reproduce

1. Remove `ports` from `compose.yml`
2. NPM reverse proxy gives 502 Bad Gateway
3. Add `ports` back to `compose.yml`
4. Reverse proxy works
5. It should work without `ports` when both NPM and Jellyseer are on the same docker network

### Platform

desktop

### Device

Browser

### Operating System

Docker on Ubuntu

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct
