### ISSUE TITLE
Jellyseerr shows "Internal Server Error" after many refreshes

### ISSUE THREAD

**Issue by sv-giampa** [Fallenbagel/jellyseerr#1092]
### Description

After refreshing many times a page containing media cards, the Web UI shows "Internal Server Error" from version 2.0.0 up to 2.1.0. And at some point, apparently at random, sonarr and radarr queues cannot be synced as shown in the posted log. This issue might be related to https://github.com/Fallenbagel/jellyseerr/issues/1091. 

Downgrading to version 1.9.2 temporarily solves the issue.

### Version

2.1.0

### Steps to Reproduce

1. Open homepage of Jellyseerr
2. Refresh it many times quickly

### Logs

```shell
2024-11-12T22:17:49.647Z [debug][API]: Something went wrong retrieving movie {"errorMessage":"[TMDB] Failed to fetch movie details: fetch failed","movieId":"106646"}

2024-11-12T22:17:49.713Z [debug][API]: Something went wrong retrieving popular movies {"errorMessage":"[TMDB] Failed to fetch discover movies: fetch failed"}

 ⨯ TypeError: fetch failed

    at node:internal/deps/undici/undici:13185:13

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async M.getInitialProps (/app/.next/server/chunks/51084.js:5:33835)

    at async X (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5045)

    at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3773)

    at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30)

    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)

    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)

    at async NextNodeServer.renderErrorToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:2189:24)

    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:2026:30)

    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)

    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)

    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)

    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)

    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)

    at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13) {

  [cause]: ConnectTimeoutError: Connect Timeout Error

      at onConnectTimeout (node:internal/deps/undici/undici:2331:28)

      at node:internal/deps/undici/undici:2283:50

      at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)

      at process.processImmediate (node:internal/timers:483:21) {

    code: 'UND_ERR_CONNECT_TIMEOUT'

  }

}

2024-11-12T22:17:59.883Z [debug][API]: Something went wrong retrieving popular series {"errorMessage":"[TMDB] Failed to fetch discover TV: fetch failed"}

2024-11-12T22:18:00.025Z [debug][Jobs]: Starting scheduled job: Download Sync 

 ⨯ TypeError: fetch failed

    at node:internal/deps/undici/undici:13185:13

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async M.getInitialProps (/app/.next/server/chunks/51084.js:5:33835)

    at async X (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5045)

    at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3773)

    at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30)

    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)

    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)

    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24)

    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1969:32)

    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)

    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)

    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)

    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)

    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)

    at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13) {

  [cause]: ConnectTimeoutError: Connect Timeout Error

      at onConnectTimeout (node:internal/deps/undici/undici:2331:28)

      at node:internal/deps/undici/undici:2283:50

      at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)

      at process.processImmediate (node:internal/timers:483:21) {

    code: 'UND_ERR_CONNECT_TIMEOUT'

  }

}

2024-11-12T22:18:10.043Z [error][Download Tracker]: Unable to get queue from Radarr server: radarr 

2024-11-12T22:18:10.045Z [error][Download Tracker]: Unable to get queue from Sonarr server: sonarr 

 ⨯ TypeError: fetch failed

    at node:internal/deps/undici/undici:13185:13

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async M.getInitialProps (/app/.next/server/chunks/51084.js:5:33835)

    at async X (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5045)

    at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3773)

    at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30)

    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)

    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)

    at async NextNodeServer.renderErrorToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:2189:24)

    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:2026:30)

    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)

    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)

    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)

    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)

    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)

    at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13) {

  [cause]: ConnectTimeoutError: Connect Timeout Error

      at onConnectTimeout (node:internal/deps/undici/undici:2331:28)

      at node:internal/deps/undici/undici:2283:50

      at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)

      at process.processImmediate (node:internal/timers:483:21) {

    code: 'UND_ERR_CONNECT_TIMEOUT'

  }

}
```

### Platform

desktop

### Device

Desktop Computer

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Oh i meant to reopen same issue 😅
But it's okay now that this is open with more information

**Comment by Fallenbagel** [comment]
I cannot reproduce the lost connection to sonarr/radarr.

How are you connecting to yhem? Through reverse proxy or internal?

**Comment by Fallenbagel** [comment]
If you're using docker can you add
`forceIpv4First=true` to your environment variables (if native install then to .env)

And also try `--dns 8.8.8.8` or if docker compose
```compose
dns:
   -8.8.8.8
```
And then see if you lose connection

**Comment by sv-giampa** [comment]
> I cannot reproduce the lost connection to sonarr/radarr.
> 
> How are you connecting to yhem? Through reverse proxy or internal?

I'm connecting through the docker stack network, but after some attempts for reproducing the bug, I now think the lost connection to radarr and sonarr might be caused by some lag in the jobs queue. This probably gets flooded when the user starts many requests in a short time.

**Comment by Fallenbagel** [comment]
> > I cannot reproduce the lost connection to sonarr/radarr.
> > 
> > How are you connecting to yhem? Through reverse proxy or internal?
> 
> I'm connecting through the docker stack network, but after some attempts for reproducing the bug, I now think the lost connection to radarr and sonarr might be caused by some lag in the jobs queue. This probably gets flooded when the user starts many requests in a short time.
> 
> 

Ah docker stack. It could be the overloading yeah we have to test it

**Comment by Fallenbagel** [comment]
> > dns:
> >    -8.8.8.8
> 
> Yes, I lost connection between Jellyseerr and Sonarr/Radarr by adding this

Huh. That shouldn't happen. So this could be related to dns. 2.0.0 onwards dns handling is very strict (bc of fetch)
Could you share your compose

**Comment by gauthier-th** [comment]
> Yes, I lost connection between Jellyseerr and Sonarr/Radarr by adding this

There is an issue with your network configuration. This shouldn't happen. That's how I got it configured on my instance (through docker network too) and everything is fine.

**Comment by ju5t-0** [comment]
Upvoting cause I'm having a similar issue issue. Had to revert to 1.9.2. I have this deployed through docker compose with other services, all of them are using the same docker network. I reach jellyseerr through an nginx used as a reverse proxy 

`⨯ TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async M.getInitialProps (/app/.next/server/chunks/51084.js:5:33835)
    at async X (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5045)
    at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3773)
    at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24)
    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1969:32)
    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13) {
  [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: localhost:5055, timeout: 10000ms)
      at onConnectTimeout (/app/node_modules/.pnpm/undici@6.20.1/node_modules/undici/lib/core/connect.js:232:24)
      at Immediate._onImmediate (/app/node_modules/.pnpm/undici@6.20.1/node_modules/undici/lib/core/connect.js:206:11)
      at process.processImmediate (node:internal/timers:483:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}`

**Comment by Fallenbagel** [comment]
> Upvoting cause I'm having a similar issue issue. Had to revert to 1.9.2. I have this deployed through docker compose with other services, all of them are using the same docker network. I reach jellyseerr through an nginx used as a reverse proxy
> 
> `⨯ TypeError: fetch failed at node:internal/deps/undici/undici:13185:13 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async M.getInitialProps (/app/.next/server/chunks/51084.js:5:33835) at async X (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5045) at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3773) at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30) at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28) at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28) at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24) at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1969:32) at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25) at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17) at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17) at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21) at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24) at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13) { [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: localhost:5055, timeout: 10000ms) at onConnectTimeout (/app/node_modules/.pnpm/undici@6.20.1/node_modules/undici/lib/core/connect.js:232:24) at Immediate._onImmediate (/app/node_modules/.pnpm/undici@6.20.1/node_modules/undici/lib/core/connect.js:206:11) at process.processImmediate (node:internal/timers:483:21) { code: 'UND_ERR_CONNECT_TIMEOUT' } }`

are you also trying to refresh many times? if not this is a different issue and we could help debug if you hop onto discord. In your case it looks like its unable to connect to the server itself

**Comment by Fallenbagel** [comment]
@sv-giampa could you give me a more in-depth steps to reproduce this or could you show a video capture? I just tried on my 2.1.0 instance by spamming refresh button several times for 2 minutes straight, and it did not throw any errors.

**Comment by sv-giampa** [comment]
I think the radarr/sonarr problem could be just a sympthom of the real one. I have no issues with 1.9.2, not even by adding

```
   dns: 
      - 8.8.8.8
```

Passing just from 1.9.2 to 2.0.0 or above (by changing the image tag), i have another problem now: the migrator component cannot migrate my configuration to the new version. Probably i need to migrate to some intermediate version between 1.9.2 and 2.0.0. I see this problem after downgraded to 1.9.2 from 2.1.0, i'll try to solve it or will open another issue.

The following is my Docker Compose stack (i use WatchTower, could it be a problem?):

```
version: '3' 
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://$HOSTNAME_LOCAL:8096/jellyfin
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config:rw             # should be a SSD
      - ${MEDIA_DIR}:/media:rw                        # should be an HDD
      - ${TRANSCODE_DIR}:/config/cache/transcodes:rw  # should be a SSD or RamDisk
    ports:
      - "8096:8096"
      - "7359:7359/udp"   #jellyfin auto-discovery
      - "1900:1900/udp"   #dlna auto-discovery
      #- "8920:8920"      #https
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_VAR_HOSTNAME=$HOSTNAME_LOCAL
    ports:
      - "${HOMEPAGE_PORT}:3000"
    volumes:
      - ${CONFIG_DIR}/homepage:/app/config 
      - ${MEDIA_DIR}:/media 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - WEBUI_PORT=9092
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${CONFIG_DIR}/qbittorent/config:/config
      - ${TORRENT_DIR}:/media
    ports:
      - "9092:9092"
      - "6881:6881"
      - "6881:6881/udp"
      - "41349:41349"
      - "41349:41349/udp"
    restart: unless-stopped
      
  jellyseerr:
    image: fallenbagel/jellyseerr:2.1.0 #1.9.2
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    ports:
      - "5055:5055"
    volumes:
      - ${CONFIG_DIR}/jellyseer:/app/config
    restart: unless-stopped
      
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}/movies:/media/movies
      - ${TORRENT_DIR}/incomplete:/media/incomplete
      - ${TORRENT_DIR}/downloads:/media/downloads

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}/series:/media/series
      - ${TORRENT_DIR}/incomplete:/media/incomplete
      - ${TORRENT_DIR}/downloads:/media/downloads

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
      - ${TORRENT_DIR}/torrents:/downloads  # watch directory

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=Etc/UTC
    volumes:
        - ${CONFIG_DIR}/bazarr:/config
        - ${MEDIA_DIR}:/media
        - /etc/localtime:/etc/localtime:ro
    ports:
        - "6767:6767"

  watchtower:
    image: containrrr/watchtower
    container_name: jellyflix-watchtower
    restart: unless-stopped
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=Etc/UTC
        - WATCHTOWER_SCHEDULE=0 0 4 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: jellyfin jellyseer radarr sonarr prowlarr bazarr flaresolverr qbittorrent homepage
```

And this is a template of my .env for the stack:

```
    PGID=1000
    PUID=1000
    HOSTNAME_LOCAL=<mDNS name or local IP of the server>
    HOMEPAGE_PORT=3000
    CONFIG_DIR=/mediacenter
    MEDIA_DIR=/mnt/hdd/media
    TORRENT_DIR=/mnt/ssd/torrent
    TRANSCODE_DIR=/mnt/ssd/transcode
```

i'll try to create a video capture after solving the Migrator problem i mentioned in this comment, but I could show you just what i have already described in the issue: open a page with media cards (e.g., home page of Jellyseerr) and refresh it many times quickly (click quickly on the refresh button of the browser); it should show you "Internal Server Error" and logs should show the errors i posted that are similar but different to the ones posted by @ju5t-0. I hope to be helpful.
