### ISSUE TITLE
HTTPS_PROXY in Docker doesn't work

### ISSUE THREAD

**Issue by xingtong00** [fallenbagel/jellyseerr#1598]
### Description

I'm using the fallenbagel/jellyseerr:last image deployed with Docker. However, I've noticed a strange issue. If I set up a proxy using the environment option, like this:
```
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      LOG_LEVEL: debug
      TZ: $TZ
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
    volumes:
      - ${APP_DIR}/jellyseerr:/app/config
    ports:
      - ${JELLYSEERR_PORT}:5055
    restart: unless-stopped
```
The program still won't use the proxy. Currently, I can only use the extra_hosts method to enable Jellyseerr to access The Movie Database (TMDb) properly. I hope to resolve this issue.

### Version

2.5.2

### Steps to Reproduce

```
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      LOG_LEVEL: debug
      TZ: $TZ
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
    volumes:
      - ${APP_DIR}/jellyseerr:/app/config
    ports:
      - ${JELLYSEERR_PORT}:5055
    restart: unless-stopped
```

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

Armbian

### Operating System

MacOS

### Browser

Edge

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct
