### ISSUE TITLE
Unavailable PROXY on container start leads to completely invalid instance

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [fallenbagel/jellyseerr#1620]
### Description

My Jellyseerr uses proxy then connect to TheTVDB and etc...
So, If proxy would be unavailable on container startup, then it would be completely broken.
No one series or movie metadata would be unreachable.
Also, if proxy starts after Jellyseerr initialization, container stay still broken until the restart.

But if proxy was working fine on Jellyseerr startup, any troubles resolves by itself.
If proxy fail after Jellyseerr container starts and then turn back, the all would work well without restart.
So, flapping of the proxy have no influence on correctly initialized container, but broke it if occurs on startup.

**P.s.** This bug occurs regularly for my server because of UPS signal to shut down. And on power on containers startup in no granted order, what leads to broken Jellyseerr. As a result, I need to restart it manually by myself.

### Version

2.5.2

### Steps to Reproduce

1. Make metadata databases unavailable for Jellyseer without proxy
2. Setup proxy for Jellyseer instance via `settings` -> `network` tab
3. Disable proxy
4. Restart Jellyseer
5. After Jellyseer initialization restart proxy
6. Got broken Jellyseer container (till the restart)

### Screenshots

|Wrong initialized container|Unavailable proxy on correctly initialized container|Well working container|
|-|-|-|
|![Image](https://github.com/user-attachments/assets/a7d1d959-3a5f-407c-bf05-e1d69af96e2d)|![Image](https://github.com/user-attachments/assets/f8bb8bba-31d5-432c-963a-90c5f0c92e2b)|![Image](https://github.com/user-attachments/assets/6eb4c367-a3a9-49c0-bc7f-3f78f95bd151)|

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

Surface Book 3, Samsung Galaxy S22 Ultra

### Operating System

Ubuntu 22.04, Windows 11, Android 14

### Browser

Edge

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

**Comment by fallenbagel** [comment]
> After Jellyseer initialization restart proxy
> Got broken Jellyseer container (till the restart)

None of the network settings will apply without a restart. You said you disabled proxy. Then restarted. Then you want it to get enabled without restart. That's not a bug. If you change a network setting you'll need to restart.

**Comment by Victor-Y-Fadeev** [comment]
> None of the network settings will apply without a restart. You said you disabled proxy. Then restarted. Then you want it to get enabled without restart. Right?

I don't change any Jellyseerr settings, including network section. When I say that I disable proxy, I meant thet i disable external container with proxy. No one setting wasn't change in Jellyseerr for all discribed cases.

**Comment by fallenbagel** [comment]
> > None of the network settings will apply without a restart. You said you disabled proxy. Then restarted. Then you want it to get enabled without restart. Right?
> 
> I don't change any Jellyseerr settings, including network section. When I say that I disable proxy, I meant thet i disable external container with proxy. No one setting wasn't change in Jellyseerr for all discribed cases.
> 
> **P.s.** Proxy settings in Jellyseerr was configured once and restarted. All other tests were after that.

The proxy settings in jellyseerr will only work for HTTP proxy. If it's not HTTP it won't work.

I guess I'm very confused. What is the issue? Are you proxying it twice?

**Comment by fallenbagel** [comment]
I have jellyseerr running with proxy enabled in settings > network and it works.

Can you share a more clear reproducible steps?

**Comment by fallenbagel** [comment]
If you're saying when you proxy from another container instead of using the internal proxy, it doesn't work, then why not use the internal jellyseerr proxy? That was added so that you can proxy through jellyseerr

**Comment by fallenbagel** [comment]
This is related to #1219 and #1542

This is expected as jellyseerr would immediately try to call tmdb to load any media if it can't it will error out. We currently dont handle that error which is what #1542 is aiming to do so.

To workaround this issue, you can make it so that jellyseerr starts when the proxy is initialised. If you're using docker you use `depends_on` feature. If its a service, you can have you can use `requires` or `after`

**Comment by Victor-Y-Fadeev** [comment]
> Edit: oh I think I understood what you're saying. So if your proxy server was down when jellyseerr started, then jellyseerr remains unreachable UNTIL you restart?

Yes, it's right.

> To workaround this issue, you can make it so that jellyseerr starts when the proxy is initialised. If you're using docker you use `depends_on` feature.

I already use this feature, but it works only if I start whole Docker Compose file at one.
In my case, server starts after power failure and does not comply startup order.

When the feature from your message planning to be implemented?

**Comment by fallenbagel** [comment]
Have you tried the health_check feature i mentioned above?

That's how immich handles it. And it works. Even after restart. If you have trouble srtting up healthcheck, please hop onto discord I'll help you with it as that's where we carry out support and its a bit hard to carry out support in github issues as its not real time

**Comment by Victor-Y-Fadeev** [comment]
So, I try several variants of test commands and test it by server/service restart.
No one helped. It works only for the `docker-compose.yml` file run.

But when container up by itself with server start, them completely ignore any dependencies.
I think this is a problem with Synology Container Manager, which unsupported startup order after restart.

```yml
name: synology

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: unless-stopped
    volumes:
      - ./config/sing-box:/etc/sing-box/
    ports:
      - 2080:2080
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
    healthcheck:
      # test: ["CMD", "nc", "-z", "localhost", "2080"]
      # test: ["CMD-SHELL", "apk add curl && curl -f http://localhost:2080"]
      test: ["CMD-SHELL", "apk add curl && curl -f -x http://localhost:2080 https://www.themoviedb.org"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

# ...

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ./config/jellyseerr:/app/config
    depends_on:
      sing-box:
        condition: service_healthy
      radarr:
        condition: service_started
      sonarr:
        condition: service_started
      jellyfin:
        condition: service_started
```

Can this issue be open until related tasks will be fixed?
I want to test them when them be done and write here the test result.
Can you ping me if docker registry tag for tests appears?

**Comment by M0NsTeRRR** [comment]
`depends_on` is a Docker Compose feature (Docker Compose is just a client for Docker with stamina—it doesn't add features to the Docker daemon). On reboot or even after running `systemctl restart docker`, the daemon restarts containers without considering `depends_on` because it's specific to Compose.  

The best approach for now is to add a health check that tests the proxy and restarts the container if needed at least until Jellyseerr handles it properly.
Just add the same health check to Jellyseerr that tries to connect to TheMovieDB through your proxy.

**Comment by Victor-Y-Fadeev** [comment]
> The best approach for now is to add a health check that tests the proxy and restarts the container if needed at least until Jellyseerr handles it properly.
> Just add the same health check to Jellyseerr that tries to connect to TheMovieDB through your proxy.

Still ignored. A Health check has no influence if container start separately. Unhealthy container wouldn't restart automatically after a server/service reboot.
```
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ./config/jellyseerr:/app/config
    healthcheck:
      # test: [ "CMD", "nc", "-z", "sing-box", "2080" ]
      test: ["CMD-SHELL", "apk add curl && curl -f -x http://sing-box:2080 https://www.themoviedb.org"]
```
