### ISSUE TITLE
2.6.0 Failed to connect to the proxy

### ISSUE THREAD

**Issue by VoidX0** [fallenbagel/jellyseerr#1717]
## Failed to connect to the proxy
- I use the following `docker-compose.yml` to start the container:
```yaml
services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    #image: ghcr.io/fallenbagel/jellyseerr:2.5.2
    container_name: jellyseerr
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr:/app/config
```
- When using the v2.5.2, the proxy works normally, but with the v2.6.0, the container throws an error:
`[error][Proxy]: Failed to connect to the proxy: : AggregateError`
- No changes were made to the proxy configuration after upgrading.

### Version

2.6.0

### Steps to Reproduce

1. docker compose down --rmi all
2. docker compose pull
3. docker compose up -d

## v2.6.0
![Image](https://github.com/user-attachments/assets/ef5431f9-4751-47ef-9576-44e49c44251e)

![Image](https://github.com/user-attachments/assets/e5505a80-2dcf-4041-9543-26ee63430232)

![Image](https://github.com/user-attachments/assets/8c612d4d-bc58-4c75-8a22-ee8ef0d11ba2)
## v2.5.2
![Image](https://github.com/user-attachments/assets/a28eff4e-a78b-4bb7-b268-d31d948cf1a8)

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

PC

### Operating System

Windows 11

### Browser

Edge

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct
