### ISSUE TITLE
[error][Auth]: Cannot read properties of undefined (reading 'Id')

### ISSUE THREAD

**Issue by Minionflo** [Fallenbagel/jellyseerr#257]
### Description

Cant get jellyseerr setup because of the error `[error][Auth]: Cannot read properties of undefined (reading 'Id')`

### Version

1.2.1

### Steps to Reproduce

1. Start it with docker-compose
2. Try to login
3. Look in the Logs with docker compose logs jellyseerr

### Platform

desktop

### Device

/

### Operating System

Ubuntu 20.04

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you try this.

1. Stop container
2. Delete container
3. Delete image
4. Pull it again
5. Re-run docker compose 

See if that works? (Ik not an elegant solution but it seems it tends to work for some users)

**Comment by Minionflo** [comment]
> Could you try this.
> 
>     1. Stop container
> 
>     2. Delete container
> 
>     3. Delete image
> 
>     4. Pull it again
> 
>     5. Re-run docker compose
> 
> 
> See if that works? (Ik not an elegant solution but it seems it tends to work for some users)

i didnt work. i still get the same error

**Comment by Fallenbagel** [comment]
> i didnt work. i still get the same error

Could you share your docker-compose?

**Comment by Minionflo** [comment]
> > i didnt work. i still get the same error
> 
> Could you share your docker-compose? Also did you remove the config folder contents before rerunning the container?

docker-compose:
```
jellyseerr:
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
        - 5138:5055
    volumes:
      - ./jellyseerr:/app/config
    networks:
      default:
        ipv4_address: 10.10.28.100
```
yes i did but it still threw the same error
