### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by Savanta** [Fallenbagel/jellyseerr#319]
### Description

Images are not loading and console keeps throwing 504 errors

### Version

 78ccea94bd37c2b44bd9409df81f2b0b898aa547

### Steps to Reproduce

1. Go to main page
2. Images not loading

### Screenshots

![image](https://user-images.githubusercontent.com/13687101/215757473-8b2d4010-5cb8-4149-be24-7622a31bb4e7.png)
![image](https://user-images.githubusercontent.com/13687101/215757522-cb254be4-1183-40a4-8489-89dff4f0185d.png)

### Logs

```shell
https://termbin.com/174r
```

### Platform

desktop

### Device

Docker

### Operating System

Docker

### Browser

Firefox, Vivaldi

### Additional Context

```
version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:develop
       container_name: Jellyseer
       user: "${UID}:${GID}"
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Warsaw
       volumes:
            - /media/Dane/.docker/jellyseer:/app/config
       restart: always
       networks:
            - InternalNPM

networks:
  InternalNPM:
      external: true
```
UID: 1000
GID: 1000

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct
