### ISSUE TITLE
请问如何设置代理呢

### ISSUE THREAD

**Issue by sy911212** [Fallenbagel/jellyseerr#343]
### Description

请问如何设置代理呢，我在设置里未找到可以设置代理的界面

### Desired Behavior

可以设置代理成功

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Proxy can be set in docker-compose as such


```
version: 'latest'
services:  
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       hostname: jellyseer
       network_mode: bridge
       environment:
         - http_proxy="http://proxy:8080"
         - https_proxy="http://proxy:8080"
         - no_proxy="localhost,127.0.0.1"
        - LOG_LEVEL=debug
        - TZ=America/New_York
       ports:
            - 5055:5055
       volumes:
            - /path/to/config:/app/config
       restart: always 
```

Or if youre running natively
```
export http_proxy="http://proxy:8080"
export https_proxy="http://proxy:8080"
export no_proxy="localhost,127.0.0.1"
```
