### ISSUE TITLE
Can't login with jellyfin auth

### ISSUE THREAD

**Issue by imrein** [Fallenbagel/jellyseerr#390]
### Description

I've been using jellyseerr & jellyfin for a while now but recently I get an issue where I'm unable to login to jellyseerr...

When trying to login using my jellyfin credentials I get an error:

`[error][Auth]: Cannot read properties of undefined (reading 'Id')`

I already setup a new and fresh container using a different volume but I have the same problem.

### Version

1.5.0

### Steps to Reproduce

1. Go to setup page for jellyseerr
2. Try signing in using my jellyfin account
3. Error

### Screenshots

![image](https://github.com/Fallenbagel/jellyseerr/assets/71074636/cd2d45c4-6eec-4b29-9eac-375648db697a)

![image](https://github.com/Fallenbagel/jellyseerr/assets/71074636/ff668a7b-0a9d-453d-8f81-942f2d826cbf)

### Logs

```shell
[error][Auth]: Cannot read properties of undefined (reading 'Id')
```

### Platform

desktop

### Device

Browser, mobile

### Operating System

Linux, android

### Browser

Firefox, Duckduckgo mobile

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Sounds like your database got corrupted

**Comment by Fallenbagel** [comment]
> That is on the jellyfin side then?
> 
> The sqlite database does not seem to be corrupted:
> 
> ```
> sqlite> pragma integrity_check;
> ok
> 
> sqlite> select * from user;
> 
> sqlite> .schema user
> CREATE TABLE IF NOT EXISTS "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar NOT NULL, "username" varchar, "plexId" integer, "plexToken" varchar, "permissions" integer NOT NULL DEFAULT (0), "avatar" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "password" varchar, "userType" integer NOT NULL DEFAULT (1), "plexUsername" varchar, "resetPasswordGuid" varchar, "recoveryLinkExpirationDate" date, "movieQuotaLimit" integer, "movieQuotaDays" integer, "tvQuotaLimit" integer, "tvQuotaDays" integer, "jellyfinUsername" varchar, "jellyfinAuthToken" varchar, "jellyfinUserId" varchar, "jellyfinDeviceId" varchar, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"));
> ```

No not jellyfin side. Jellyseerr side

**Comment by Fallenbagel** [comment]
Could you try a test container pointing to a different config folder and see if it logs in?

**Comment by imrein** [comment]
Hmmmm very weird, the following things give the same result:

- Docker container with bind mount
- Docker container with different bind mount
- Docker container with volume mount
- Docker container on different systems (amd64 & arm64)

**Comment by imrein** [comment]
My `docker-compose.yml` file:

```
---
version: "3"

volumes:
  jellyseerr_data:

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_data:/app/config
    restart: unless-stopped
```

**Comment by Fallenbagel** [comment]
Hmm. Thats weird. Could you try the manual method?

**Comment by imrein** [comment]
Nope still the same, I also can't pinpoint exactly when this happened...

**Comment by Cromsite** [comment]
Same problem, I can't log in.

**Comment by imrein** [comment]
Nah doesn't work, tried multiple other users as well but same error.

**Comment by Cromsite** [comment]
I confirm it doesn't work. A complete reinstallation of Jellyseer and Jellyfin did not work either.

**Comment by imrein** [comment]
So it's working for you now?

**Comment by Cromsite** [comment]
Yes, it's working now. recently worked from external address "https://host.host.ru" now only "IP:PORT" I don't know what happened.
This seems to have happened after updating Jellyfin to version 10.8.10. But, not sure.

_I'm sorry for my English, I'm using Google Translate._

**Comment by imrein** [comment]
Hmmm, I'm still having the same issue. I don't access my jellyseerr externally so I just use the local IP.

![image](https://github.com/Fallenbagel/jellyseerr/assets/71074636/e2ce2d4c-99e1-47b3-88df-2e996887af8d)

**Comment by Fallenbagel** [comment]
> Hmmm, I'm still having the same issue. I don't access my jellyseerr externally so I just use the local IP.
> 
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/71074636/e2ce2d4c-99e1-47b3-88df-2e996887af8d)
> 

Can I see the dockercompose

**Comment by imrein** [comment]
```
---
version: "3"

volumes:
  jellyseerr_data:

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_data:/app/config
    restart: unless-stopped
```
