### ISSUE TITLE
Suddenly can't sign in using Jellyfin Account, log has username set as e-mail

### ISSUE THREAD

**Issue by Bush-cat** [Fallenbagel/jellyseerr#608]
### Description

Yesterday I setup Jellyseerr and it worked great, on the next day I couldn't log in with Jellyfin anymore, nothing changed. 
When I click sign in, it says "signin in" for minutes, then fails with "username or password is incorrect", my login still works on jellyfin but not on jellyseerr, I then tried to delete the whole container and start it from scratch, removed jellyseerr from jellyfin devices and deleted the jellyseerr configs. now on the new setup I got the same problem and can't sign in with jellyfin.
I tried changing the Jellyfin adress in the settings but it didn't help either

I noticed something odd in the logs, the failed attempt says email: Bushcat which is the Username I entered, there's no Username field or my email address as value to be found in the message.
shouldn't it be more like
{"account":{"ip":"::ffff:192.168.111.22","email":"something@mail.com","username":"Bushcat","password":"__REDACTED__"}}

### Version

v1.7.0

### Steps to Reproduce

1. Open Jellyseerr WEBUI
2. Sign in with Jellyfin
3. Wait 5 Minutes until it fails
4. Open Docker Logs

### Logs

```shell
$ NODE_ENV=production node dist/index.js
yarn run v1.22.19
2024-01-02T12:16:27.510Z [info]: Commit Tag: $GIT_SHA 
2024-01-02T12:16:29.177Z [info]: Starting Overseerr version 1.7.0 
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
2024-01-02T12:16:34.860Z [info][Server]: Skipping starting the scheduled jobs as we have no Plex/Jellyfin/Emby servers setup yet 
2024-01-02T12:16:34.837Z [info][Notifications]: Registered notification agents 
2024-01-02T12:16:35.765Z [info][Server]: Server ready on port 5055 
2024-01-02T12:20:18.535Z [warn][Auth]: Failed login attempt from user with incorrect Jellyfin credentials {"account":{"ip":"::ffff:192.168.111.22","email":"Bushcat","password":"__REDACTED__"}}
```

### Platform

desktop

### Device

X86_64

### Operating System

Windows 11

### Browser

Firefox & Chromium

### Additional Context

my Docker Compose of Jellyseerr and Jellyfin
```yaml
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/jellyseerr:/app/config
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    network_mode: "service:gluetun"
#    ports:
#      - "${WEBUI_PORT_JELLYSEERR:?err}:5055"             # Configured in Gluetun VPN container

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/jellyfin:/config
      - ${FOLDER_FOR_MEDIA:?err}/media:/data/media
      - ${FOLDER_FOR_MEDIA:?err}/cache/jellyfin:/cache
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - JELLYFIN_PublishedServerUrl=${LOCAL_DOCKER_IP:?err}  # Enable for DLNA - Only works on HOST Network Mode
      - ROC_ENABLE_PRE_VEGA=1 # needed for transcoding on AMD GPU
    network_mode: 'host'
    ports:
      - "${WEBUI_PORT_JELLYFIN:?err}:8096"
      - 7359:7359/udp                 # Enable for DLNA - Only works on HOST Network Mode
      - 1900:1900/udp                 # Enable for DLNA - Only works on HOST Network Mode
```

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct
